openapi: 3.0.3
info:
  title: SMART KITCHEN API
  description: SMART KITCHEN用API
  version: 1.0.0
  contact:
    name: sasakura
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: currentUser
    description: ログインユーザー情報
  - name: users
    description: ユーザー情報
  - name: presignedUrl
    description: S3の署名付きURL情報
  - name: recipes
    description: レシピ情報
paths:
  /auth/sessions:
    get:
      tags:
        - currentUser
      summary: ログイン中のユーザー情報を取得する
      description: ログイン中のユーザー情報を取得する
      operationId: getCurrentUser
      parameters:
        - name: uid
          description: devise-token-auth用のuid
          in: header
          required: true
          schema:
            type: string
        - name: access-token
          description: devise-token-auth用のaccess-token
          in: header
          required: true
          schema:
            type: string
        - name: client
          description: devise-token-auth用のclient
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/currentUserResponse.yml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /users/{userId}:
    get:
      tags:
        - users
      summary: 単一のユーザー情報を取得する
      description: 単一のユーザー情報を取得する
      operationId: getUser
      parameters:
        - name: userId
          description: ユーザーのID
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getUserResponse.yml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    patch:
      tags:
        - currentUser
      summary: ログイン中のユーザー情報を更新する
      description: ログイン中のユーザー情報を更新する
      operationId: updateCurrentUser
      parameters:
        - name: uid
          description: devise-token-auth用のuid
          in: header
          required: true
          schema:
            type: string
        - name: access-token
          description: devise-token-auth用のaccess-token
          in: header
          required: true
          schema:
            type: string
        - name: client
          description: devise-token-auth用のclient
          in: header
          required: true
          schema:
            type: string
        - name: userId
          description: ログイン中のユーザーのID
          in: path
          required: true
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/updateCurrentUserRequest.yml"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/currentUserResponse.yml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /presigned-url:
    get:
      tags:
        - presignedUrl
      summary: S3の署名付きURLを取得する
      description: S3の署名付きURLを取得する
      operationId: getPresignedUrl
      parameters:
        - name: uid
          description: devise-token-auth用のuid
          in: header
          required: true
          schema:
            type: string
        - name: access-token
          description: devise-token-auth用のaccess-token
          in: header
          required: true
          schema:
            type: string
        - name: client
          description: devise-token-auth用のclient
          in: header
          required: true
          schema:
            type: string
        - name: userId
          description: ログイン中のユーザーのID
          in: query
          required: true
          schema:
            type: number
        - name: fileName
          description: S3にアップロードする予定のファイルの名前
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getPresignedUrlResponse.yml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /recipes:
    get:
      tags:
        - recipes
      summary: レシピ情報を一覧取得する
      description: レシピ情報を一覧取得する
      operationId: getRecipes
      parameters:
        - name: limit
          description: 取得するレシピ情報の件数
          in: query
          required: true
          schema:
            type: number
        - name: offset
          description: 取得をスキップするレシピ情報の件数
          in: query
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getRecipesResponse.yml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    post:
      tags:
        - recipes
      summary: レシピ情報を登録する
      description: レシピ情報を登録する
      operationId: createRecipe
      parameters:
        - name: uid
          description: devise-token-auth用のuid
          in: header
          required: true
          schema:
            type: string
        - name: access-token
          description: devise-token-auth用のaccess-token
          in: header
          required: true
          schema:
            type: string
        - name: client
          description: devise-token-auth用のclient
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/createRecipeRequest.yml"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "./schemas/createResponse.yml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /recipes/{recipeId}:
    get:
      tags:
        - recipes
      summary: 単一のレシピ情報を取得する
      description: 単一のレシピ情報を取得する
      operationId: getRecipe
      parameters:
        - name: recipeId
          description: レシピのID
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getRecipeResponse.yml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
