openapi: 3.0.3
info:
  title: SMART KITCHEN API
  description: SMART KITCHEN用API
  version: 1.0.0
  contact:
    name: sasakura
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: currentUser
    description: ログインユーザー情報
paths:
  /auth/sessions:
    get:
      tags:
        - currentUser
      summary: ログインユーザー情報取得
      description: ログイン中のユーザーの情報を取得
      operationId: getCurrentUser
      parameters:
        - name: uid
          description: devise-token-auth用のuid
          in: header
          required: true
          schema:
            type: string
        - name: access-token
          description: devise-token-auth用のaccess-token
          in: header
          required: true
          schema:
            type: string
        - name: client
          description: devise-token-auth用のclient
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#components/schemas/currentUserResponse"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
components:
  schemas:
    currentUserResponse:
      description: ログイン中のユーザー情報のルートプロパティ
      type: object
      required:
        - user
      properties:
        user:
          description: ログイン中のユーザー情報
          type: object
          required:
            - id
            - name
            - comment
            - image_url
          properties:
            id:
              description: ユーザーID
              type: integer
            name:
              description: ユーザーネーム
              type: string
            comment:
              description: 一言コメント
              type: string
              nullable: true
            image_url:
              description: ユーザーの画像のURL
              type: string
              nullable: true
        
    
